

# Model Configuration
model_path: "/data/wangyiyan/cardinality_estimation_wyy/model/t5-large"
# model_path: "/home/valiantsec/phb/models/codet5"


# Dataset Configuration
data_path: ./data/train_stats_finetune.json
# Dataset Configuration
max_length: 1000  # 输入序列的最大长度

# Training Configuration
output_dir: "./result/t5_large_stats_ft_v4_1e-5"
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1e-5
lr_scheduler_type: "linear"
warmup_ratio: 0.1
num_train_epochs: 13

# Saving and Logging Configuration
save_strategy: "steps"
save_steps: 1000
logging_steps: 50
evaluation_strategy: "steps"
eval_steps: 1000

# LoRA Configuration
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
